# Generated by Django 4.1.5 on 2023-07-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecast',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
