# Generated by Django 4.1.5 on 2023-07-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0002_alter_weatherforecast_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecast',
            name='detailing_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
