# Generated by Django 4.1.5 on 2023-07-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0006_weatherforecast_latitude_weatherforecast_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherforecast',
            name='base',
        ),
        migrations.RemoveField(
            model_name='weatherforecast',
            name='cod',
        ),
        migrations.RemoveField(
            model_name='weatherforecast',
            name='name',
        ),
        migrations.RemoveField(
            model_name='weatherforecast',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='weatherforecast',
            name='visibility',
        ),
        migrations.AddField(
            model_name='weatherforecast',
            name='forecast_data',
            field=models.JSONField(null=True),
        ),
    ]
